services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - .env  # Load all environment variables from .env
    restart: unless-stopped  # Restart policy

  db:
    image: postgres:13
    env_file:
      - .env  # Load PostgreSQL-related environment variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # Restart policy

volumes:
  postgres_data:
