services:
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the entire project directory
    depends_on:
      - db
    env_file:
      - .env  # Load all environment variables from .env
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped  # Restart policy

  db:
    image: postgres:13
    env_file:
      - .env  # Load PostgreSQL-related environment variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # Restart policy

volumes:
  postgres_data:
