"""Add poster_url to TVShow and set default values

Revision ID: 2b3a57bc835c
Revises: b96e6c6c3b13
Create Date: 2024-11-27 20:40:52.296987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3a57bc835c'
down_revision = 'b96e6c6c3b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_show', sa.Column('poster_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_show', 'poster_url')
    # ### end Alembic commands ###
